### ISSUE TITLE
Migration du réseau physique en Gigabit

### ISSUE THREAD

**Issue by nashe** [ungdev/Projets#1]
Le réseau actuel repose sur un switch 100Mbps alors que nous en avons récupéré un Gigabit il y a peu.

Il faudra migrer correctement la configuration (surtout les VLAN aha) depuis l'ancien vers le nouveau, faire quelques tests, et ensuite tout basculer sur le nouveau.

Le nouveau switch _top of rack_ est chez @hugocollignon, il faut voir avec lui pour qu'il le ramène à Troyes ;-)

**Comment by hugocollignon** [comment]
Yop'

L'archi et complètement achevée, y a plus qu'a deployer.
Il est chez moi le temps de le configurer.

2016-03-30 13:09 GMT+02:00 Thomas Chauchefoin <notifications@github.com>:

**Comment by hugocollignon** [comment]
La migration a été effectuée ce week-end, tout s'est bien passé ! Les premiers résultats prouvent une nette amélioration (temps de snapshot par exemple).
